#!/usr/bin/env bash
cd "${0%/*}" || exit                                # Run from this directory
. "${WM_PROJECT_DIR:?}"/wmake/scripts/AllwmakeParseArguments

#------------------------------------------------------------------------------

foamv=${WM_PROJECT_VERSION}
min_ver=2306

if [[ $foamv =~ ^v([0-9]{4})$ ]]; then
    ver=${BASH_REMATCH[1]}
    if [ "${ver}" -lt "${min_ver}" ]; then
        echo "Error: OpenFOAM-${foamv} detected. This branch requires OpenFOAM v${min_ver} or newer."
        exit 1
    fi
else
    echo "Error: Unrecognised OpenFOAM version '${foamv}'. This software only supports OpenCFD versioned releases (e.g. v2306)."
    exit 1
fi

#------------------------------------------------------------------------------

wmake src/lagrangian
wmake src/loadPolicies
wmake src/cpuLoad
wmake src/errorEstimators
wmake src/dynamicMesh
wmake src/dynamicFvMesh
wmake src/functionObjects

wmake applications/utilities/updateMesh
wmake applications/solvers/combustion/reactingDyMFoam
# -----------------------------------------------------------------------------
